main: me.daanhautekiet.economy.Main
name: EmeraldEconomy
author: Nohty
version: 1.0.0
api-version: 1.16
commands:
  EmeraldEconomy:
    aliases: ee
  Withdraw:
    aliases: with
  Deposit:
    aliases: dep
